/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ff24e822-22de-4c82-834c-c00a31c497bf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ajfIz4oPh",
    "aws_user_pools_web_client_id": "2dnoajmlp56ljh2p97ce14eo4d",
    "oauth": {
        "domain": "wms-mxitgo.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8000/dashboard",
        "redirectSignOut": "http://localhost:8000/user/login",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;