/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0654ad78-a1e7-4799-b868-ccad336068cc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9WJ8uxbk9",
    "aws_user_pools_web_client_id": "66vntbnp4mpgn1o1p50pqd43kl",
    "oauth": {
        "domain": "wms-mxitgo.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.d330t61iyxm7gh.amplifyapp.com/dashboard",
        "redirectSignOut": "https://dev.d330t61iyxm7gh.amplifyapp.com/user/login",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;